language: node_js
node_js:
    - "0.12.2"
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - npm install
script: 
    - gulp
    - npm install -g karma-jasmine
    - ./node_modules/karma/bin/karma start karma.conf.js --browsers Firefox --single-run
after_script:
    - echo "Build executed!"

